name: my_app
description: "A new Flutter project for real estate dashboard."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  fl_chart: ^0.66.1
  provider: ^6.0.5
  intl: ^0.18.1
  supabase_flutter: ^2.0.0  # هذه الحزمة تجلب postgrest تلقائياً
  flutter_dotenv: ^6.0.0 
  csv: ^5.1.1 
  path_provider: ^2.1.3
  url_launcher: ^6.2.6
  shared_preferences: ^2.1.1

  # 🛑 تم حذف postgrest: ^a.b.c
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env